"""Adding Sexo Column

Revision ID: 1a9ec82dac1f
Revises: d088ddde680a
Create Date: 2022-12-30 16:02:52.077391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9ec82dac1f'
down_revision = 'd088ddde680a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sexo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sexo')
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###
