"""release 3

Revision ID: d89e656763d2
Revises: e0c41305ce8e
Create Date: 2022-12-29 22:41:23.660265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89e656763d2'
down_revision = 'e0c41305ce8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
