"""Adding column ativoe

Revision ID: e0c41305ce8e
Revises: c95c0c97b0e1
Create Date: 2022-12-29 22:39:14.276259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c41305ce8e'
down_revision = 'c95c0c97b0e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ativo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ativo')
    # ### end Alembic commands ###
