{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(up, instance)" } },
   { "name": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "Handler",
    "query": {
     "query": "label_values(http_requests_total, handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average response time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"$Job\",handler=\"$Handler\"} / http_request_duration_seconds_count",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status, job, method) (http_requests_total{handler=\"$Handler\", job=\"$Job\"})",
     "legendFormat": "{{status}} - {{job}} - {{method}}"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"$Job\",handler=\"$Handler\"}[$__interval])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"5xx\",job=\"$Job\",handler=\"$Handler\"}[$__interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (increase(http_requests_total{job=\"$Job\", handler=\"$Handler\"}[$__rate_interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(http_requests_total{job=\"$Job\",handler=\"$Handler\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"$Job\",handler=\"$Handler\"} / http_request_duration_seconds_count",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "sum by (Handler) (histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{job=\"$Job\",handler=\"$Handler\"}[$__interval])))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\",job=\"$Job\",handler=\"$Handler\"}[$__interval]) \n/ ignoring (le) increase(http_request_duration_seconds_count[$__interval])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{job=\"$Job\",handler=\"$Handler\"}[$__interval]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"$Job\"})",
     "legendFormat": "{{instance}}{{job}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"$Job\"}[30s]))",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$Job\"}",
     "legendFormat": "{{instance}}{{job}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$Job\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  }
 ]
}