version: '3.8'

services:    
  rabbit-mq:
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672
    # environment:
    #   METRICS_PROMETHEUS: "true"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:15672"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    # restart: always
    # deploy:
    #   mode: replicated
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 800M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 800M
    #   restart_policy:
    #     condition: on-failure
    #     delay: 5s
    #     max_attempts: 3
    #     window: 60s