version: '3.8'

volumes:
  app01: {}
  postgres: {}

services:
  # app01:
  #   build: ./
  #   volumes:
  #     - app01:/usr/app
  #   # ports:
  #   #   - "8000:8000"
  #   expose:
  #     - "8000"
  #   environment: 
  #     USER_DB: "postgres"
  #     DATABASE_DB: "postgres"
  #     HOST_DB: "postgres"
  #     PASSWORD_DB: "changeme"
  #     PORT_DB: 5432
  #   depends_on: 
  #     - postgres
  #     - proxy
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.app01.rule=Host(`app01.localhost`)"
  #     - "traefik.http.services.app01.loadbalancer.server.port=8000"
  #   restart: always
  #   networks:
  #     - app
  #   deploy:
  #     mode: replicated
  #     replicas: 5
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 250M
  #       reservations:
  #         cpus: '1'
  #         memory: 250M
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 60s

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app  

  proxy:
    image: traefik:v2.8
    command: 
      - '--api.insecure=true' 
      - '--providers.docker'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
      - '--providers.docker.watch=true'
      - '--providers.docker.exposedbydefault=true'
      - '--log.level=DEBUG'
      - '--entrypoints.web.address=:80'
      - '--accesslog=true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
      - '8081:8080'
    networks:
      - app  
    deploy:
      restart_policy:
        #condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        delay: 10s
        order: start-first
        parallelism: 1
      rollback_config:
        parallelism: 0
        order: stop-first
    logging:
      driver: json-file
      options:
        'max-size': '10m'
        'max-file': '5'
        
networks:
  app:
    name: app